---
name: Feature Request
description: Have an idea for a new feature? Ask away!
labels: ["enhancement"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description of feature
      description: When you perform what command or action, what do you think should happen?
    validations:
      required: true
